### ISSUE TITLE
Don't work gausu_deizaru.c

### ISSUE THREAD

**Issue by NotFounds** [L2E0/hamakawa-lab#5]
Is this correct?
When I input this data, this program outputs wrong answer. 
```
3
2 -4 6 5
-1 7 -8 -3
1 1 -2 2
```

I expect this outputs.
```
2.2 0.0 0.1
```

**Comment by L2E0** [comment]
Apparently there seems to be some matrix that can not solve the equation.
So why don't you try to input identity matrix.
I get correct output if I do this.

**Comment by NotFounds** [comment]
@L2E0 thx
